name: "Scheduled validation"

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * *"

permissions:
  contents: read

jobs:
  validate:
    name: "Validate"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: "Run repository validation"
        uses: ./.github/actions/build
